<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.tiktok</groupId>
        <artifactId>live-user</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>

    <!-- 原工程此处硬编码特殊 groupId com.tl.user，现收编统一继承 com.tiktok -->
    <artifactId>live-user-interface</artifactId>
    <packaging>jar</packaging>

    <name>live-user-interface</name>

    <dependencies>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
        </dependency>
    </dependencies>
</project>
