server:
  port: 8082
#
#spring:
#  application:
#    name: tl-live-user-provider
#  cloud:
#    nacos:
#      discovery:
#        server-addr: nacos.tllive.com:8848
#        namespace: tl-live
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://192.168.65.210:3306/tllive?useUnicode=true&characterEncoding=utf8
#    username: root
#    password: root
#  data:
#    redis:
#      host: 192.168.65.210
#      port: 6379
#      lettuce:
#        pool:
#          min-idle: 10
#          max-active: 100
#          max-idle: 10
#
#dubbo:
#  application:
#    name: ${spring.application.name}
#    qos-enable: false
#  registry:
#    address: nacos://nacos.tllive.com:8848?namespace=tl-live
#    id: nacos-registry
#  protocol:
#    name: dubbo
#    port: -1

#tllive:
#  sms:
#    ccp:
#      # 测试环境，实际发短信。
#      test: true
#      smsServerIp: app.cloopen.com
#      port: 8883
#      accountSId: 2c94811c8cd4da0a018ed0dfe87f5a6d
#      accountToken: f9f296ec8f2546658add9cb6947abf25
#      appId: 2c94811c8cd4da0a018ed0dfea165a74
#      templateId: 1
#      testPhone: 15874260244